version: '3'

services:
  app: 
    volumes:
      - ./ytdlp-bin:/ytdlp-bin
    build:
      context: .
      dockerfile: dockerfile
    tty: true
    command: "bash ./scripts/startup.sh"
    ports:
      - "8777:3000"
